---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: akv2k8s
  chart:
    spec:
      chart: akv2k8s
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: akv2k8s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      keyVaultAuth: environment
      # env:
      #   AZURE_TENANT_ID: 
      #   AZURE_CLIENT_ID: id_xyz
      #   AZURE_CLIENT_SECRET: sec_xy
    env_injector:
      keyVaultAuth: environment
  valuesFrom:
      - kind: Secret
        name: az-kv-sp
        valuesKey: tenant_id
        targetPath: global.env.AZURE_TENANT_ID
        optional: false    
      - kind: Secret
        name: az-kv-sp
        valuesKey: client_id
        targetPath: global.env.AZURE_CLIENT_ID
        optional: false 
      - kind: Secret
        name: az-kv-sp
        valuesKey: client_secret
        targetPath: global.env.AZURE_CLIENT_SECRET
        optional: false                 
