apiVersion: v1
stringData:
    user: ENC[AES256_GCM,data:GjwyJLQPhkM8HdjR,iv:l96ac1Ze6R+exncoA9Jt1lIUM5M2jnPqpgWAGHTB6PQ=,tag:MNB61CoTA4HUI/EPtNS0HQ==,type:str]
    userb: ENC[AES256_GCM,data:HUhpKGzVGHGQGTBpcg==,iv:vQZ9gSO/VrXd0c+17neWApCeGFAj6muvGCl2fFUbfB4=,tag:3sofJfQ0NyV5yYIeDB660w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ1FJUFkvMVYybEVYcEZs
            aitrL0Y5QXJJbkkvNGZwbHpSR3BKbDN5SlZVCkViM1lvYmhwelFpK0JJbjluY0pX
            YzZZNzFOQ2JsbjRSNWFXWU5nRVBPRjQKLS0tIGVWeENCQ3loei9vc0RHVGN4bVp1
            QWxaOTdTVThrLzNlSDdLcnpWbjAySUEK3p0yVke+b+S1o2tFOThH0uXb1+S7eSWE
            PyhDovvmWOT+bjvE4JFwRXA2BgjiSqK10UPsMtFK5r+dF5wHIe5Odg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T16:05:04Z"
    mac: ENC[AES256_GCM,data:S0mCmRnFJDSvk6Rs7mDpVS5WW1xHD9BphL5RZ/NsOroorydU7iFfMXAmVIlj73Erh6/YKbMscxMkiN5YxzySeRVOlLJ35U8/r6bR4vOs85DL9Hfzed0Esm4+QX/zbHvdDE583uokT1cDfp/aLnFQ12e4xsv3LbvLn49nExbh+CA=,iv:JWsyXtbCqK7acio6tkg6mjvOk/HllwtJ0i6RBMMl/uo=,tag:N7SBqYmBCQtAB4X70KlSCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
