apiVersion: v1
stringData:
    user: ENC[AES256_GCM,data:qQdr1rpk33ou5g6s,iv:/giZ0P09krPmr9V3l9JNrAJPKc7MobjsRMU1wU/NVVM=,tag:D/yUTBiL3A6Px4xDERtONg==,type:str]
    userb: ENC[AES256_GCM,data:0koVe/M=,iv:UeCK2YiQoWKmLr7K3V7VfJyBaquE979UQ1YV0TuR/xg=,tag:L7k91YCLaZSemPooas8tZQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVVvbGV5dlFUZ0xuNVdH
            aWVncis1dWIyRGZlV2NUcklqYVRBazJRRWcwCmJDa0VzVkpYSm1wL09ZQyt2c0ww
            K1lNRkJDUUJ6ZzByaktLSThQY1lreGsKLS0tIDczaCtKNlpTTllrRjNuSXJSS3o2
            ME9UdEhFMG9jZmhTd1N0NjhJd1RsaFEKuV2I4r1zntkIa3E47v88q5IH9Y3no+BO
            ozUFM5OMX8KXnzhDUfY3dgXAhZjo2hB2a7Pp7XQabFmBX3kokvWW3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T14:41:37Z"
    mac: ENC[AES256_GCM,data:kfHO01UtOqUOXZs6AGCXCnoXeuEdqJQMKgttJsV+VJLMHmPVhRSRQlnDP2pQrgx+e7+rquEEJ7z0wX/GJE08PkcGApFYzCZ2Bc/HGoPOJ0Y/TSCFFROh16sVAPcxNGVfupOjUidV3cjanFkxIx2j8F2XwpLJYpBxAKCQwg+RAu4=,iv:aC+6XytVrXE5DfRq8rL9TqQevBR8263jhgaxUx+q8TY=,tag:/bVhQ8N1HvumUXbGkBiPPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
