apiVersion: v1
stringData:
    identity: ENC[AES256_GCM,data:S5BgWPCctLnwXLcc5X7fT6k93KUhKFMAY55KlL7dD9NgGQpVvz/WDK8JNMHWqiyp0pmqo1yCFJcLxDso7+pV+P86OXBVvjfi/D0f1SGZ64xG1Mgp81AIQZ6jrz7KZZ1Lf5c9G82GUgx46bYCFsrgJxHX/x1Yer6mLHXqOB3j8norYT1cUF5EqfIew3zeRdxnH3STq2yTDOw29EAW1Yx8uMqV/s2L2syIDwAuZxBdvzdtuQ15ybiJayX7tQiyrarZFeQoK9YORD+3sMJR30MD63YYRPFVJFy1urv93t/dEmC5HgBt93q7KBZLOmiqqZpcpgTlBHuHzf3KqgLYCcMKGZxz52yn7g6qpTFczSWqyuGkXx91rFLLrkuZncgvmrJIRbXrQVutz1LerZbukd4fS763ZpsRJRSQYiLmTfpwg6RJCinw1OAXK+1h4DTUHtS5/mcR9KQeIhJvEQxVIoc+V1qGZ9t/O85h9cxf8IeDUahYUyzdyQHIzRz4bEiqc/vrNkdEt4F5BgRXAZIcjgCAB4PQ73pjdWlXDQVHD/WOuifPjQvwNnlHp8Xfg7moJMEER72AGft0vhZvpnNw01kx7vSJcPoyICfSPyJ/bxoozA==,iv:y4XfldbqQrcIcgVB/I2sc6U9+H5x/aut3nv2UpLNpHM=,tag:S1Bon/pM0hYKQRGHI+lwpQ==,type:str]
    password: ENC[AES256_GCM,data:5zH/hwIamDK7,iv:5YwaD+UyCHkpssdxaePFZminIm9oOmaYMeYdLaf4BCE=,tag:9LluMsrfkvipLXXY0SxOFQ==,type:str]
    some_key: ENC[AES256_GCM,data:3wsZDHdocqYXtdo=,iv:WnZ6/dRUAWbhcES68/lsAeWm+xKlUBuZt5W2UxVQzVU=,tag:sYy2oCoUNLp2isLWyIaXLw==,type:str]
    known_hosts: ENC[AES256_GCM,data:o8+uKodsW1FzW9J9ozMDmyy2GdU9LK7TRxYsGMSD/uS1yQPzSYupHR7nbzZiI8AWq2tPQjgJJIkYQqm1rphnr/48EYLEjwcs6gq9pMwrWpFv2a12srCrZClM7mDs0vCYoZB64iDfPO9wNO6wO+3Ro2NJ4CK5BElsYLbdaWf/HNi0DLwV6rBlVHbbonG+FxIg9xLyFkuA8awdv2EEdm2WaAClc5EnyFhvItGoRxPGrFROy5gwruwjhyNmrfAIcWQDB3bzTO1GIqrkgwJa2wLMcOhui90BmcqY1448TPOfcYqsO9FpmS7sZXFT/Y4xCVbHX5iCja6TFeyArUp5YCaHlxJX9vm56IaNOgWzSStNY9InwAo+beMIBIoM6qf6sOzITw73d/DpdyOX2RUN9rTXPTezmh3megzcXBVDlZAJu5Xw3VLAmWeiMtZH638d9uNfEkwFy+p+gAa2E4/W/f9iPp/CuNDLKwsl/oSiV9jCuBTU5oDph+o56UvaWXwQzMsu93xZkBv1678I1SURTzBNXRKzMa8fj3HME8SaeZ8WWsCQDbXih2Updzou740RBTutmj0FBnMnl/AEArTViSf+CqT+acjvYEpzJS9Ir3ER3k0LbZczBYgW5XqDBzJ2vDVRTflWQ7t1BlDiaMrm+NKkUZqTqvt1gYwdJb4ArEN8jSnH1SWFgW/ribCmbfXG/blaHxMaRtr7Y3wBRpaTzX0yHXdbRtf3cg1JqzaBnGayOM4mz8Zr+O6wLh1JdOKJkDYy2AV4JISTp4g++JR6lguJDWm3k5WZwfnVMtnGRmg/cZH4ReP0v0iIqK3LIo4EvzT75T+8QZXk4W/RIGI3Kn+Mz44r1mbE6sOc42KuLlHZCijxfUcAjoMiMhBoQ22q4flb5nrcZZ/A/waKcmgzW3RjUwuA2udIeahE0NSV8FnKZa9mX2oV5ugfMi5gxpysbNk38Lg2ifGrksu0PV8E23kvde71zvar1Syx3CQcC3a+qNdZrswnve9vShvFTC/MP+o8Gw5WFUNaLwdelNTRjy3Debr6eKvPfh5IMgwr2g99cCvUQjWsjfB1ustfAC0nJ2MmMDJlJ/FZql3DNvM=,iv:aQsMb2jMqxlBwI9t8HRTDloJfeuesEMEIQruo4bEmQQ=,tag:pj9+lHzOwtZD8wnlR0J/Ug==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gh-ssh-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsekV2NDJ0djRJbzlmQU1G
            aWhvMkxMaWN3eldYaFRLWmI5WC83QThkMHk4CkVFczNOSE9pa3dSeVJqZ1IyT3pq
            RWxVRStPZEEvV3lhem9OdllmSm85OU0KLS0tIEtiL3VmaXlhQldyN1pUZjErWXJv
            YXFlTElLb3hyTkpYZ0JEL1FJd3pYTU0KHremdgpWICUMygv09rqImAs7bu3u3vKq
            QlCeFDtg5HNe38nmhOfZcr9B/zhxdpVF/v32AUuVom8E4oZQfVtrtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T15:46:39Z"
    mac: ENC[AES256_GCM,data:nlX3/WtzbmwHMvB0a7kZvL4/rhKKAKB+xQjJxXEB5G2BXr3KnsAc02/55T4iVK3eVUqf8iD2e+yLTsNKQlZKjtKk6I12XlKq59mbn95kElyIgqDguZVZqDbH+FmHHiIt54XomIZagG8DYYjGIleMMTcLNEuMcVPmuYtAABxBCGQ=,iv:4CjHqyElGl9bnUPtTMs6SF7golUZBpXqfEsCo37vka0=,tag:2z18XKH/K7mn77zLGh10Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
