apiVersion: v1
stringData:
    identity: ENC[AES256_GCM,data:oV0vVPbCTMBt8eZ8zfniK07Kwd/oUB7hhakkz/Feu5PjCb0XRdjIIVUKZDWb1ZGXHfDnC6Dl4Pdv7jjATFUW7gAWoJ6aBe5u+FcGfjPpgJaN9YgcMl42quu4uyF+UEyHY58762CAAve0RQDjxbGQodMZoyV9KNMDApHmxRP4uubZHbTEIxMb1qwjPDMB3GhO0kZSuob4urEgDTUb0Wla+T0bfUGXpZY+iW9ErmmwDrj0y6DzpDepb7JkwMcfVy/CLl6Zztb3t1j9jSzM79ikCi8KZxyOD+dK81y3f9W/HkCVYq+gLyGBr3EM+seWhimvVK4lYzB3yOQVPob2rxgDveHQVedvJoz633TSPhZRqUOlJ6K/bWrAe4J1J3uJMYVPzJzHkySCeY5UCeRXKAAZbStGKkcl5ilMA31VPA9cn7I1nA2I1nPXhL8AqB8vjp1QviDUFCAY1KR4M5wpafjDeN4KP/jNWYIQD6vdsbtJR8dyh59P7F/VH4O3Uq0mLTuwX454knG+vTJ7ByXqDAwU1nx8WQkBct9qn68eyZV2BMlazIsgCBkvEVNmOPfcn/AScBovziXwQNJNeGo5xi4SQ2W9Of0Dn8ylrAkjZpGV3Q==,iv:rbFwSkb/tYIrQmWTEBGPyACPwMGMBdRvfiBWceIYbeA=,tag:u/UHf9d+QeTy5cwHYhyZRg==,type:str]
    password: ENC[AES256_GCM,data:wAbZ12vsmmG4,iv:OjnRMOHjqn9fZMeEqyOdYjx5iivm+fq5Pl2l80Wleik=,tag:dJUtVoX3RSIXDrqoDpT8hg==,type:str]
    some_key: ENC[AES256_GCM,data:5d5Vug==,iv:DsuU7qSbZ44rgjT/rYNihxw2k6vpGY6xWwRVZwuHdZA=,tag:XUsAwRvXo5QPpAKm6lgHTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:uoWwTLG569M+1T8NlIbc486p/2uLoyNp9DXBaQWLZpAvoHsvMu+sRhGVcRqJvx4sl6DKj7amxzllYH/dtmdk8iCIp36r1zADQeqQwgriJF7UDU/L2uB7y10MGCzuBHvp8wlI3Tg1cTPvuSE9p1EjSracR3i3FtrY/Ys1PlQmFvd0lKBI6ETaK1zkHvvVPgAO8wN980HW9ZLEA4OHb4NVBgulTCp8jfNNptqxOTq0UXRJXFhYZP8u8eI6J6qYoUpi9XG2oPCMzb9TdyEpk+kr0b1I1p+fK2GL0nOwfF3UtE/zwGScfltinbe35nj3aZrY39AYTti7yoZaUMGDV5g2vdlte+s0ku8f9hYDrwdsGhltkGKP38iDBpRbdrO/7GHEydp5Mh0JuJjx0MBFlnZt+LWtTnGWQewIuzKFRDKbSK+0hWHI5QwRhFSF4cSvYoERCytGIskF2REBq3+55iUejBaL7zfZuAB1U5PJtqdtFe+kjVq1bZlXqKkMigId0O1/9pw8cB7npF3OtLQC8IxKeCPwwOdA9QhGsHvVlp2pA+hbjyIL11EofhlzE7uIuNEIknsKxeVnY05ag/35MCstEOhLcs/aXrtHRfIMmWIZun0KttutJ+TXsOlhkMPOKMIvMigDapMTkufLqw8UpnC7wKCnX2mO10hzjFM0fDFodBGaP0b95cjqMxHQ/1NkQd3C1LI8En0UHpBzp5ifpd5yRq/6Psw3fKwxXKYPX/5vq0bDTsP2uo9n0WadD8YIOcEaLvWdY7pEL65O4RQzWLmbVKrMcP3a3sMI3tz+DLIZ7nmYD8xJdmLna4fxK7nqgz1ApIVZlJGsFb41O+1oZX6ovQZehyBK6Cs3DHrN2Bexi8Cq6aisrEz16pGqyITTCd/hYAGV1z+Q1rAPLPLqdZBOmgU93q6UYE4ZwNQA/Ak1sLYJbJpm3wNPOuopHZo56eEphGZ2ESqxW/MdE7YwZMVedHsi37CiYPpiD6DYrXWIpUgrAqiJFBAhxwibBI0lDf/zAwRwtnlHT28Ynv+amRj9Era46T0xJmB2rHFClCjbiwTlxRx9Yy2H7FRqCUjqFSMqQyi5dzKuS8FByS8=,iv:+P0JdbAE0N6wlTYYE1lUODRl1hRo+XlCryEh/+STMUI=,tag:lJHIfEmxS9njTMFe2pQ2hw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gh-ssh-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RU94Um1EZTF0R3JGMXpw
            dUtMMDlTeFhaQlJ4ZEFTY3BmYnBQRTZ6dHlJCnQrT1ByN0dqYUMrb2ZORnRycnBw
            ckYyQ1RIbG1nMm1kM24zNyt4Wk13cXcKLS0tIGJHdUxGVSt4ZW1KaWRHSno2bEhT
            cUorSk1seHlXakxlSXNZd0FYbXE0YVUK8OEf44mWSpe/Cz47ozL3NmIUOCQEZ49a
            leJWBhZAvjwTKJ4xEznE4qb39+18YCOaZJPSsOVIZ3qQ9/03xQxhKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T15:40:14Z"
    mac: ENC[AES256_GCM,data:/HwGk75ieMfKvn2CMYee9gVYA/5Ms0OkWca2voBHFcHUzFkKXZJ3PlT3ADPFhY7jD0VSfm3SQz7s5il1+Ta0FcFK96h8Xe74zPvIDCvajYbgDm28Q9/zV1LNXVMfsNahOxD1C4R/rYDVo0+emJMbQFSooiFZ4b6ED+H5/YBfje8=,iv:RqRhmYyZlTjpg18x111duXuYk1eGYIlVmmV+0dElXqM=,tag:banzg+GLsSKZCUZRgq/miw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
