apiVersion: v1
stringData:
    identity: ENC[AES256_GCM,data:9/5FT4G0716vQDWpmdu0QCf4/bGHXvs98R86/dvCF8vxRNWuNT1px8KOqZKtO0y6eQI6BJbRs3BMhIUHGcQpDKkrNl6XtmdmoBMCkRUkBwAzzuSYOiqy5auf4J7WhLnkYAgBHdBX71tq0rzQu3/6c4ifOgn9+EMVknTqULK9R5oGuMSE+0jaugHpCNrDgb7BuoMkha140Y1IcQt3W2fzsZRUKdok/QC2Vkh8q4LxGhptItGK1+T4ud5cJEK9mmdB2lNZSyB+xxcPHfaDwDH0sg6xFeZD9klVdoOYhSrh++cLpjvzGX2dNjQ9tMtKGWsw1JMJtd5T40uE9ETy24M3pTbORB/Pju2V9pSksPxZSy8Y3HjABhqmjhHy4mdD+wowQ3AffuH3uXW089La9iZPkiY3EM11gu/CEyyb+OmsKwb6JI/ku4OFG+oOS8RtdCVLpxBbzuILy1p8CTFxlIQSKl6V01tsRkkf6F52CT7lda+aJpkVPacn5NrgP9RTCnS/Y+LHUnGuMHt8c5SGx5bPxN4ovEngpIBAFgSpn2O+VezhQ36nLJXRa0QJeoOK1M1y3NymCIZ4ZgSOv8IburIv7hlYGujhf3Xr4qah1jXCbA==,iv:ZCClKYbul1zcWo+/o5toNxhoISDDrKgjbivzkTxnZh4=,tag:e7DRxN0bjp5+fqiwgfc+rw==,type:str]
    password: ENC[AES256_GCM,data:Mng1pCxnqB+z,iv:DxdEVjjiAEsOOZTLP2zOvw8uQarjhFqeHyPHbBduABw=,tag:WjLZ0+Bc+UBhEAdZ2qzEvQ==,type:str]
    some_key: ENC[AES256_GCM,data:7LxyhA==,iv:19Vm2BbAuwEstEyndPcIKZhYnrlAo4CLsECwLH5fhOI=,tag:RBD9WBPXCabqYfO1T8f2PA==,type:str]
    known_hosts: ENC[AES256_GCM,data:4OSFXiycofGgmRqPecd2luUltPJRcyPnmtk9rUq7EC2wbQG3L+73kCnFvwf/YKNiQWA3bTeS6wApeNaWdY6l1uPqd2H/4ZoeDnpOhXeXR/weDE9FqajyODAN8mKJ5SJ/4G2BY8eDbJ4+TVXXJ16fEG7DlYZMv70pYZYE6jmJhCZ+zyzziBln3/oYVYx6SmLCKxYmyIUu9poK0jjCarl2ehSpURcTnZ+AoYkdaVCBJH1dpLwi2IYOF5Gx3BZ25firxB7LQRRGx4RM5rdWRqiFzJgbFXX2tB0DxdeR/asp0/C4W3aUfRawpzqDXQvWmZXkuEhIvw7bHrRpkP99qKk1uBejJjBrqBGlRJ3DmHDR2TgkjSwu0rLEhBGGIBzIjhNhZ3txiYl531Fgj+KdPQQayypWfg+SXKeghpI1j/2g6neLJ03pNv1HW/aMO3rjU5CJRxKaa6bRtSBRDHoQzdtPODZrOI0io7/WfdXELIkENoQYlKf43gHfCs5rwx+K5q2L+RSGSKHv7JgU0hDkZJskIXWvMvaX3aMAMkfnsEzMHBOQKAjbpWnwnZ6S69vPBGAH4JeKtfZNUt4E9RMEp7PbUd/h4Uyowd5otkog3MBk0tK1+/p9JWDroNd/7cEq+5LYPE1dwKvp6PISL25C2lDqA9yDisrhPTdRWNWv9sBR9Jd6Q8qIHiVbjXKB+P3nmsedZm+dX1NqJARlKHxB6rM6tCclrkQvm1xokpAHJ6H3xIQXGSX9dGaD8NtuHLTQtefby3U5BU4vMOvbdu7KA+VR1cBJhmtSoWCu9wNjiUF1nvdWEMSopSTJ9lD26sV6Kf/WhO6K9IN1taZnUwwApB3DOt5uOReU/4zeH4e1RHs44JxoW8XoAnYwFnUvUvIz+Fked0V+hZPP5iF7osftpYNuD6HrXMvB7Lk1VxTGhUQii/s2UUjsOibX+MpyG/TSmRnybHBZQgXbUzVb8V7imI5aSJZuwgo/wGn6dmWmyRJiC/ccG2zVjR3be1V8YqWi90MfyULnfB/XCgRjz2UjrvfnlAGxj9zP1jTG/JHkF74ZgU2wKS0Hwy/jQb+g9MP4rYCQpZsORVimr/pvt9I=,iv:yiLnEyZYjeBDBkwF9i1rwdy2XgWYtVnDbz+sWs/MTeo=,tag:N7cQAn8T+l/CHiTyNOdY4Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd0RZS3VrcFpRT2FIOFBU
            NDlPUS8xWVpjS2hlK0hWQ2oxWTF4bGVZZUZRCnZiOXVPUm4rUjFtZjY5VTArVUpm
            bTQxcCtQN2dHOVEvc01WMEV3TWY1YmsKLS0tIG12Tk1UTW5nK2ZKRUhqWGZ6OC81
            TExvSzdnQy8yNWJGK0NVTDQvNFFwRHMKpYo5oHmQVtYZBa6GqmdyRybbce2Uroi/
            4gj4iBY6Ic140ADqdo1/O9x9zDhOaKiGLGDHgPTHDzLd4OmGbjCIbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T15:02:20Z"
    mac: ENC[AES256_GCM,data:iedFbThLkL5XfsFMCCV/IHQyRvOoGjWXXV4njAoHtwStrlob3keTyB1xLvZ+i3O3lR9Ur9YzQmaBIXhIEafiPN3yvBheNKIXDbDdBXhp3go6r39X4ZsrK9Gzm/TRZs/4Yx6ARkTRAcic7xBqfO84iWwvS55E9ob6y+eFhNBfW4U=,iv:9c1GwY7OCQ0v3Wcc0fHRH7D1POS7y29+kJnTwcweda4=,tag:3PQycPk/NoBBnyUDTFaFmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
