apiVersion: v1
stringData:
    identity: ENC[AES256_GCM,data:3xMEGLybLn+gMiqCo4Cr1OiJXB4pg7O5W36M7bEkRMLPGEpK+IxI9sgIN/JWb2LANl9s8bRyxqJ4GEAiXAXPRr0Mq43r/XTTVyR6yGf2yL04McepF3qA0b1kMRXOx7/whYsg6TzHeop7AQi3a3nA1cAtKeHJC3oKKzYSX5KFjq0+TaqbD/IQMw4aWB95d5ii1d4tSIvPy09J7q2xuK12vHDjsnUAT45wtbtiUD6zfln417tiK3iATbrP3K4RndEOPbiM3wfLxcgzdf9gTe1LaaYz2QKOWGwgLbKw/kRHZ8oDvlhM4iDS+EQxxKNrwJtJdQ9bshlHSYlSsiyRYJfGLUggt73GSGX7R0a9VsVkyck2jGSldxF16/MZosQrITSGAzwp4+lsgvYH5cSbxSGeJ/cw7YnYY9hfbIjf1K2tICmDT8aOaDlQF1tgspWBc4PN1WzXMVNR3O9LSeoogW1rTtOevT8q6W8OtPPSdeN+5/yUUH/T2KRnyaSxE1tpujVUyJg8JLsJ3/1ZUwtexcP1mAchffw5jkGdEzghKl4leG1xEnrDIrbFFNA1gHhIaOHsNvIaR4PNWqsV42lKBk7QiZY2Py48HMqLqEnGDbyhjg==,iv:WeAABn2W3yvYD33PjkoDkMZCTioBd8I0Yp/Lknmve78=,tag:K39eiapyeblAhOH3/ogqlQ==,type:str]
    password: ENC[AES256_GCM,data:YsPwKit6p3dn,iv:47FoyHWeEeIic1IxKhKBqupSmLUHU0wcxu9/iEyo62s=,tag:o6GKQcc0y4EUOKtpCxJmoQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:R0lL99SYJyowoZjQa0wNibsSEVsPZfqyEL6D3clANXgmNq2pu/VWLsj9F27cN9u/9N45A+n1z0AVMwXojy7n7Lx9JiWYl/FPW5B6LyxkXVY3S6qE+hx91L5+ziaLqCnphiFYLX4hALS4taGkQP+dLdG8pGNk0qUBc97kuwgGx+ZvOlRRXDVzOfX5Z4vYUVVxeYuzN6bLb8MG2QioyXns+AhCzAChblR5R65rYoz9e1oFauW9cP+yGBE0DhO7Qq7Rc42jUh7sdwSXkStZRY9NEIWirlb4PYXRSxa0K0N4bsHLjiHsLG6uFnXRolhhhPs6ZCpKCKZGghb8luiu/UVCI845jEKoLxPjyQv95OmDLPfpkIAsxR2iCMgbYTBX58+2iKCwjNVC14JT/KIICCjCMojhhWls9REa3Noz5yuTKv67m+B1kUa7KRIWxNrZ6t9w7RqlmJHJNDle0B8gKVOpSWMdAChwgw0rz66XjwcsbbhdPndD1e2fjZEX2X9Bry2dt4a17oDZMC3WvrbrGdt/kGktQkzmw9NU3fmzfE5sH3gTOrtLQhgWFVNGhkH5Nh8N1s0g4XozJeBTxkoRlHgREJSWDFPSA+r6hO1Zn1UdN0hCX8HlnirP0y7joF129ubt/nedxgn4E8y7szGUxupqCtzQsC7iFTS2LWCm21xb8cXcwTpaO1JTXRN+VVB0IJKZLOEOz3QfWIbEdE6CpBeo+V+5pDJys+8npVgnaASwFrdbjqX1TKXI5Ts9HBbUnuOQXAtMVBP6jDra4FbAx36nHnxHF+OXVgpbVdC2xw+YDPNtoIOuQPMl7NMe/iLfNsaps5z94cmMMW9yomwSTkME2fQs3dgROTYzuWHhHq8wJdxLHTUuWBJPr38Ss69TlpcQdly7U0bIVzISPZWhTxfE46mMtmRdxqO+WLiyqNx4k5Qf9hollmUy3ZxLYRKsTdFtwMvUIxk8ROxBs0UYFLiP6sOw3ktLeJpdEuNuzBRs2+RcnlcDZWjxHBhY4uTuf/oiT4cpUvgDEMTxvwcTHuLXZUS0UkmptATJbukr2N9VbTk+CVSixU6iIS+hYFvfdUYpA+0u3WHZBQSv5y4=,iv:marGWC9uq+ntEIhfU17+BuYP/qGP4Vgk6XJKNtpYWvk=,tag:tV4q+Z9Etox3s9pAJHdTpw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gh-ssh-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15d29xvesmwptv0rxzj3xzrpg73hqc00m5elu403j6p830uer2ars74s559
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeHlMam5qRm5KMVNxVjFw
            MWFKQ1I3Ri9ieEdGMkJKRVR4dHNkWWk1K3lZClVuQmErYVVpeEJIWDF6UHhqNith
            aWsyOFBqdmV1WGIyb1VrRGdBYUViLzQKLS0tIGMrQXl4VC9zcDhIM2lOOTEvTWIz
            SVErK0srdEoyUWljK0JoSVhEZGZvOEkKHxvByW7V7+dPliuwOTV/2bIuAp5CV7l1
            Ggbwq4+12/rU5510JoGVy1jR8LRK6IBHfOpLCnmVRszGvurVPxsJyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-08T15:49:37Z"
    mac: ENC[AES256_GCM,data:EGY4i+Q9q8iyfgAw5U3sI1S21oeEXA1fi2U+mQQ921K2vsTz2R5f4QBouVHUtSpOcH9zXL18VQWouh3M+Pyqw2EI4DKb39nghLQRzzlavUON0ymAperH6A/Ld3VOncnx1gYdKSg0LbKS7PjPkKxmTjjGhbjArun85CD7NWtkFp4=,iv:3GUlPgf3FgxGkSQvEaoocTJmFE2hWx+ebL9aYhEIakA=,tag:QKI+Ra1g32PaZes7C0WBOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
