apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: podinfo-secret-sync 
spec:
  vault:
    name: home-lab-kv # name of key vault
    object:
      name: podInfoSecret # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: podinfo-secret # kubernetes secret name
      dataKey: secret-value # key to store object value in kubernetes secret