---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  path: ./kubernetes/production/infrastructure/external-secrets/external-secrets/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-lab-fleet-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: akv2k8ss
      namespace: akv2k8s
  interval: 30m
  retryInterval: 1m
  timeout: 3m